[project]
name = "jax_test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "gdtk",
    "jax[cuda13]>=0.8.0",
    "numpy>=2.3.4",
]

[tool.uv.sources]
gdtk = { path = "../../../GDTk/gdtk.robust-python-modules/src/gdtk-py", editable = true }

[tool.ruff]
line-length = 100

[dependency-groups]
dev = [
    "ipython>=9.7.0",
]
